name: vector_math
version: 1.4.5-dev
author: John McCutchan <john@johnmccutchan.com>
description: A Vector Math library for 2D and 3D applications.
homepage: https://github.com/johnmccutchan/vector_math
environment:
  sdk: '>=1.0.0'
dev_dependencies:
  browser: any
  hop: '>=0.30.3 <0.31.0'
  unittest: '>=0.10.0 <0.11.0'
